version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    container_name: mocachic-app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - quality-net
networks:
  quality-net:
    driver: bridge
    external: true
