services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    container_name: mocachic-app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'
    networks:
       - quality-net

networks:
  quality-net:
    name: quality-net
    driver: bridge
    external: true