version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    container_name: mocachic-app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - mocachic-network

  nginx:
    image: nginx:alpine
    container_name: mocachic-nginx
    ports:
      - "81:81"
      - "444:444"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./nginx/mocachic/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - mocachic-network
    restart: always

networks:
  mocachic-network:
    driver: bridge
